/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jh_jni_JniTest */

#ifndef _Included_com_jh_jni_JniTest
#define _Included_com_jh_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jh_jni_JniTest
 * Method:    open
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jh_jni_JniTest_open
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
